# docker build -t network_butcher .
# docker run --name nn --rm -v $(pwd):/network_butcher -it network_butcher

FROM ubuntu:22.04

ENV MY_DIR=/network_butcher
ENV TZ=Europe/Rome


# Install build requirments
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install wget build-essential cmake git libtbb-dev --no-install-recommends -y
#RUN apt-get update && apt-get install build-essential git libtbb-dev --no-install-recommends -y
#RUN apt-get install python3.8 python3.8-dev python3-pip --no-install-recommends -y

# Compile python from source - avoid unsupported library problems (https://stackoverflow.com/a/70866416)
RUN apt-get update &&  apt-get install -y software-properties-common


RUN add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt install -y python3.8-dev python3.8-distutils

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.8 get-pip.py

# Install python libraries
WORKDIR ${MY_DIR}
COPY dep/requirements.txt .
RUN python3.8 -m pip install -r requirements.txt


# Install lastest version of CMake (https://askubuntu.com/a/865294)
#RUN apt-get install wget dirmngr gpg-agent software-properties-common lsb-release --no-install-recommends -y
#RUN apt-get clean all
#RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 42D5A192B819C5DA
#RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
#RUN apt-get update && apt-get install cmake --no-install-recommends -y


# Prepare for the test_run
COPY . .
RUN mkdir -p test_build
WORKDIR ${MY_DIR}/build

RUN cmake -DCMAKE_BUILD_TYPE=Release -S .. -B . -DPYTHON_EXECUTABLE=/usr/bin/python3.8
RUN cmake --build . --target test_run
RUN ./test_run --gtest_color=yes

CMD bash