name: Documentation Deployment

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install doxygen graphviz mscgen dia

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory.
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_PROTOBUF_SOURCE=ON -DUSE_GOOGLETEST=ON -DDISCOVER_COMPLETE_TESTS=ON -DENABLE_PARALLEL=OFF -DUSE_OPENMP=OFF -DUSE_PYBIND=ON -DBUILD_DOC=ON

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target doxygen

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{github.workspace}}/build/doc/html # The folder the action should deploy.